name: Build and push Docker images

on:
  push:
    branches:
      - master
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |

          cd alert-service
          ./gradlew build
          docker build -t ahmedgodaa/alert-service:latest .
          docker push ahmedgodaa/alert-service:latest
          
          cd ../irrigation-service 
          ./gradlew build  
          docker build -t ahmedgodaa/irrigation-service:latest .
          docker push ahmedgodaa/irrigation-service:latest
          
          cd ../sensor-service
          ./gradlew build     
          docker build -t ahmedgodaa/sensor-service:latest .
          docker push ahmedgodaa/sensor-service:latest
