openapi: 3.0.3
info:
  title: My service
  description: My service
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
    description: 'Local server'
paths:
  /api:
    get:
      summary:
      description:
      responses:
        '200':
          description:

