apiVersion: v1
kind: Service
metadata:
  name: alert-service-service
  namespace: development
spec:
  selector:
    app: k8s-test
    env: development
    version: v1.0.2
  ports:
    - protocol: "TCP"
      port: 8082
      targetPort: 8082
  type: ClusterIP