apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-service-deployment
  namespace: development
  labels:
    app: alert-service
    env: development
    version: v1.0.1
spec:
  selector:
    matchLabels:
      app: alert-service
      env: development
      version: v1.0.1
  replicas: 1
  template:
    metadata:
      labels:
        app: alert-service
        env: development
        version: v1.0.1
    spec:
      containers:
        - name: alert-service
          image: ahmedgodaa/alert-service:v1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
#          readinessProbe:
#            httpGet:
#              port: 8082
#              path: /actuator/health/readiness
#            periodSeconds: 300
#          livenessProbe:
#            httpGet:
#              port: 8082
#              path: /actuator/health/liveness
#            periodSeconds: 300
#            initialDelaySeconds: 300
          env:
            #    < ------------              ConfigMap           ------------ >

            # Server
            - name: ALERT_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: alert-service-configmap
                  key: ALERT_SERVICE_PORT

            # MongoDB
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: alert-service-configmap
                  key: MONGODB_DATABASE

            - name: MONGODB_PERSIST_NULL_FIELDS
              valueFrom:
                configMapKeyRef:
                  name: alert-service-configmap
                  key: MONGODB_PERSIST_NULL_FIELDS

            - name: MONGODB_AUTO_INDEX_CREATION
              valueFrom:
                configMapKeyRef:
                  name: alert-service-configmap
                  key: MONGODB_AUTO_INDEX_CREATION

            # Service Discovery
            - name: ALERT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: alert-service-configmap
                  key: ALERT_SERVICE_URL

            - name: IRRIGATION_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: alert-service-configmap
                  key: IRRIGATION_SERVICE_URL

            - name: SENSOR_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: alert-service-configmap
                  key: SENSOR_SERVICE_URL

            # Actuator
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              valueFrom:
                configMapKeyRef:
                  name: alert-service-configmap
                  key: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE

            - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
              valueFrom:
                configMapKeyRef:
                  name: alert-service-configmap
                  key: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS

            - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: alert-service-configmap
                  key: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED

            - name: MANAGEMENT_HEALTH_LIVENESS_STATE_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: alert-service-configmap
                  key: MANAGEMENT_HEALTH_LIVENESS_STATE_ENABLED

            - name: MANAGEMENT_HEALTH_READINESS_STATE_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: alert-service-configmap
                  key: MANAGEMENT_HEALTH_READINESS_STATE_ENABLED

            #    < ------------              Secrets           ------------ >

            # MongoDB
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: alert-service-secret
                  key: MONGODB_URI

            # Firebase
            - name: FIREBASE_CREDENTIAL_TYPE
              valueFrom:
                secretKeyRef:
                  name: alert-service-secret
                  key: FIREBASE_CREDENTIAL_TYPE

            - name: FIREBASE_CREDENTIAL_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: alert-service-secret
                  key: FIREBASE_CREDENTIAL_PROJECT_ID

            - name: FIREBASE_CREDENTIAL_PRIVATE_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: alert-service-secret
                  key: FIREBASE_CREDENTIAL_PRIVATE_KEY_ID

            - name: FIREBASE_CREDENTIAL_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: alert-service-secret
                  key: FIREBASE_CREDENTIAL_PRIVATE_KEY

            - name: FIREBASE_CREDENTIAL_CLIENT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: alert-service-secret
                  key: FIREBASE_CREDENTIAL_CLIENT_EMAIL

            - name: FIREBASE_CREDENTIAL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: alert-service-secret
                  key: FIREBASE_CREDENTIAL_CLIENT_ID

            - name: FIREBASE_CREDENTIAL_AUTH_URI
              valueFrom:
                secretKeyRef:
                  name: alert-service-secret
                  key: FIREBASE_CREDENTIAL_AUTH_URI

            - name: FIREBASE_CREDENTIAL_TOKEN_URI
              valueFrom:
                secretKeyRef:
                  name: alert-service-secret
                  key: FIREBASE_CREDENTIAL_TOKEN_URI

            - name: FIREBASE_CREDENTIAL_AUTH_PROVIDER_X509_CERT_URL
              valueFrom:
                secretKeyRef:
                  name: alert-service-secret
                  key: FIREBASE_CREDENTIAL_AUTH_PROVIDER_X509_CERT_URL

            - name: FIREBASE_CREDENTIAL_CLIENT_X509_CERT_URL
              valueFrom:
                secretKeyRef:
                  name: alert-service-secret
                  key: FIREBASE_CREDENTIAL_CLIENT_X509_CERT_URL

            - name: FIREBASE_UNIVERSE_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: alert-service-secret
                  key: FIREBASE_UNIVERSE_DOMAIN