apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: development
spec:
  project: default
  source:
    directory:
      recurse: true
    repoURL: https://github.com/AhmedGodaa/IrrigationSystemBM.git
    targetRevision: HEAD
    path: kubernetes/development

  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true