apiVersion: v1
kind: Service
metadata:
  name: sensor-service-service
  namespace: development
spec:
  selector:
    app: sensor-service
    env: development
    version: v1.0.1
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081
  type: ClusterIP