# Project Configuration should be in Environment Variables Like This server.port=${PORT}
# And Come From K8 Secrets but for now we will use this
server.port=8445
spring.data.mongodb.uri=mongodb+srv://banquemisr:nvfYiV4HHsj4FVkE@banquemisr.r01q6gc.mongodb.net/
spring.data.mongodb.database=banquemisr
spring.data.mongodb.persist-null-fields=true
spring.data.mongodb.auto-index-creation=true




