name: Build and push Docker images

on: 
  workflow_dispatch:
    inputs:
      version:
        description: Image Version
        default: v1.0.0
        required: true
        
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Alert Service Docker image
        run: |
          cd alert-service
          ./gradlew build
          docker build -t ahmedgodaa/alert-service:${{ github.event.inputs.version }} .
          docker push ahmedgodaa/alert-service:${{ github.event.inputs.version }}

      - name: Build and Push Irrigation Service Docker image
        run: |
          cd irrigation-service 
          ./gradlew build  
          docker build -t ahmedgodaa/irrigation-service:${{ github.event.inputs.version }} .
          docker push ahmedgodaa/irrigation-service:${{ github.event.inputs.version }}


      - name: Build and Push Sensor Service Docker image
        run: |
          cd sensor-service
          ./gradlew build     
          docker build -t ahmedgodaa/sensor-service:${{ github.event.inputs.version }} .
          docker push ahmedgodaa/sensor-service:${{ github.event.inputs.version }}
